/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Enable_Left_aliases.h"
#include "Enable_Left.h"
#include "Motor_R_F_aliases.h"
#include "Motor_R_F.h"
#include "Motorpwm_right.h"
#include "Clock_1.h"
#include "Motorpwm_Left.h"
#include "Enable_Right_aliases.h"
#include "Enable_Right.h"
#include "Motor_L_F_aliases.h"
#include "Motor_L_F.h"
#include "Motor_R_R_aliases.h"
#include "Motor_R_R.h"
#include "Motor_L_R_aliases.h"
#include "Motor_L_R.h"
#include "mode.h"
#include "ADC_calR.h"
#include "ADC_calL.h"
#include "cal_R_aliases.h"
#include "cal_R.h"
#include "cal_L_aliases.h"
#include "cal_L.h"
#include "ADC_calR_IRQ.h"
#include "ADC_calR_theACLK.h"
#include "ADC_calL_IRQ.h"
#include "ADC_calL_theACLK.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

